config/routes.rb
Rails.application.routes.draw do
  resources :likes
  resources :comments
  resources :themes
  resources :images
  resources :values
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root 'main#index'
  get 'main/index'
  get 'main/help'
  get 'main/contacts'
  get 'main/about'

  match 'signup', to: 'users#new', via: 'get'
  match 'signin', to: 'sessions#new', via: 'get'
  match 'signout', to: 'sessions#destroy', via: 'get'
end

app/views/shared/_footer.html.haml
%footer.mastfoot.mt-auto
    .inner
        %p
            = "Oborin Pavel © | "
            = link_to "🇷🇺", locale: :ru
            = link_to "🇬🇧", locale: :en

app/views/shared/_header.html.haml
%header.masthead.mb-auto
    %div.inner
        %h3.masthead-brand Experteeze
        %nav.nav.nav-masthead.justify-content-center
            - if signed_in?
                .dropdown.nav-link
                    %div.dropdown-toggle{:id => "dropdownMenuButton", :type => "button", "data-toggle" => "dropdown"}
                        = gravatar_for current_user
                    .dropdown-menu
                        = link_to t('.profile'), current_user, class: "dropdown-item"
                        = link_to t('.sign_out'), signout_path, class: "dropdown-item"
            - else
                = link_to t('.sign_in'), signin_path, class: "nav-link"
            =link_to t('.home'), main_index_path, class: "nav-link"
            =link_to t('.contacts'), main_contacts_path, class: "nav-link"
            =link_to t('.help'), main_help_path, class: "nav-link"
            =link_to t('.about'), main_about_path, class: "nav-link"